. /etc/static/bashrc
. "$HOME/.config/zsh/env"
. "$HOME/.config/zsh/path"
. "$HOME/.config/zsh/alias"
. "$HOME/.config/zsh/prompt"
source /nix/store/9kj8g4xd7m6n7phbklj6paz5wk1avkq1-fzf-0.33.0/share/fzf/key-bindings.zsh

# Switch to Solarized Dark if we are currently in dark mode
if [[ "$(uname -s)" == "Darwin" ]]; then
  val=$(defaults read -g AppleInterfaceStyle 2>/dev/null)
  if [[ $val == "Dark" ]]; then
    export OS_THEME="dark"
    rm -f ~/.config/kitty/light.theme.conf
    pkill -USR1 kitty
  else
    export OS_THEME="light"
    ln -sf ~/.config/kitty/Tomorrow.conf ~/.config/kitty/light.theme.conf
    pkill -USR1 kitty
  fi
fi
