#!/bin/zsh

function symlink() {
  ln -sfv "`pwd`/$1" $2
}

mkdir -p $HOME/.config
for conf in ./home/.config/*; do
  symlink $conf $HOME/.config/
done

symlink ./home/.config/ssh/      $HOME/.ssh
symlink ./home/.bin              $HOME/.bin
symlink ./home/.config/zsh/zshrc $HOME/.zshrc
symlink ./home/.config/vim       $HOME/.vim
symlink ./home/.config/vim/vimrc $HOME/.vimrc
