#!/bin/zsh

function symlink() {
  ln -sfv "`pwd`/$1" $2
}

for conf in ./home/.config/*; do
  symlink $conf $HOME/.config/
done

symlink ./home/.bin $HOME/.bin
symlink ./home/.config/zsh/zshrc $HOME/.zshrc
